"""Core protocols and data transfer objects for the infrastructure layer.

Follows Clean Architecture / Dependency Inversion Principle:
Nodes depend on these abstract protocols rather than concrete vendor implementations
(e.g., Groq, Cerebras, Tavily).
"""

from dataclasses import dataclass
from typing import Protocol, runtime_checkable


@dataclass
class LLMResponse:
    """Standardized response from any LLM provider.

    Attributes:
        content: Text response content generated by the model.
        tool_calls: Parsed tool calls if requested and provided by the model.
        model: Specific model name that generated the response.
        provider: Provider name (e.g. 'groq', 'cerebras', 'openrouter').
        usage: Token usage statistics (prompt_tokens, completion_tokens, total_tokens).
    """

    content: str
    tool_calls: list[dict] | None = None
    model: str | None = None
    provider: str | None = None
    usage: dict[str, int] | None = None
    finish_reason: str | None = None
    reasoning: str | None = None
    latency_seconds: float = 0.0
    # None means the provider/model has no pricing metadata in this repository.
    # We intentionally do not invent a price for arbitrary open-source endpoints.
    cost_usd: float | None = None


@dataclass
class SearchResult:
    """Standardized result entry from a search provider.

    Attributes:
        url: Direct link to the source document or webpage.
        title: Title of the document or webpage.
        content: Main text snippet or summary extracted.
        raw_content: Optional full raw page content if retrieved.
    """

    url: str
    title: str
    content: str
    raw_content: str | None = None
    published_date: str | None = None


@runtime_checkable
class LLMProvider(Protocol):
    """Protocol for LLM interactions.

    Implementations must be async to allow non-blocking execution and integration
    with the Concurrency Gate.
    """

    async def complete(
        self,
        *,
        prompt: str,
        tools: list[dict] | None = None,
        max_tokens: int | None = None,
    ) -> LLMResponse:
        """Generate a completion from the LLM given a prompt, optional tools, and max_tokens."""
        ...


@runtime_checkable
class SearchClient(Protocol):
    """Protocol for web search queries.

    Implementations must be async to allow concurrent searches.
    """

    async def search(
        self, *, query: str, max_results: int = 5
    ) -> list[SearchResult]:
        """Execute a web search query and return standardized search results."""
        ...
